const EMOJI_KEYWORDS_MAP: Record<string, string> = {
  // Smileys
  '😀': 'grinning face happy smile',
  '😃': 'grinning face big eyes happy smile',
  '😄': 'grinning face smiling eyes happy smile',
  '😁': 'beaming face smiling eyes grin happy smile',
  '😆': 'grinning squinting face laugh haha',
  '😅': 'grinning face sweat cold sweat relief happy',
  '😂': 'face tears of joy laughing cry lol haha',
  '🤣': 'rolling on the floor laughing rofl haha',
  '😊': 'smiling face smiling eyes happy blush shy',
  '😇': 'smiling face halo angel innocent',
  '🙂': 'slightly smiling face',
  '🙃': 'upside-down face silly crazy',
  '😉': 'winking face wink blink',
  '😌': 'relieved face calm peace',
  '😍': 'smiling face heart-eyes love like adore',
  '🥰': 'smiling face hearts love warm',
  '😘': 'face blowing a kiss kissy blow',
  '😗': 'kissing face',
  '😙': 'kissing face smiling eyes',
  '😚': 'kissing face closed eyes',
  '😋': 'face savoring food delicious tasty tongue',
  '😛': 'face tongue out silly',
  '😝': 'squinting face tongue out',
  '😜': 'winking face tongue out wink silly',
  '🤪': 'zany face crazy wild goofy',
  '🤨': 'face raised eyebrow suspicious skeptical',
  '🧐': 'face monocle investigator smart detective',
  '🤓': 'nerd face smart geek glasses',
  '😎': 'smiling face sunglasses cool chill sunglasses',
  '🥸': 'disguised face glasses mustache mask spy',
  '🤩': 'star-struck amazed wow star',
  '🥳': 'partying face party celebrate horn hat',
  '😏': 'smirking face smirk sly',
  '😒': 'unamused face meh bored unimpressed',
  '😞': 'disappointed face sad regret',
  '😔': 'pensive face sad depressed reflective',
  '😟': 'worried face anxious concerned',
  '😕': 'confused face unsure puzzled',
  '🙁': 'slightly frowning face sad',
  '☹️': 'frowning face sad',
  '😣': 'persevering face struggle trying hard',
  '😖': 'confounded face frustrated',
  '😫': 'tired face exhausted weary',
  '😩': 'weary face tired sigh',
  '🥺': 'pleading face puppy eyes beg sad cute',
  '😢': 'crying face tear sad weep',
  '😭': 'loudly crying face sob weep sad tears',
  '😤': 'face steam nose win angry triumph',
  '😠': 'angry face mad annoyed',
  '😡': 'pouting face angry mad rage red',
  '🤬': 'face symbols mouth swearing cursing angry mad',
  '🤯': 'exploding head mind blown shock amaze',
  '😳': 'flushed face embarrassed shocked blush',
  '🥵': 'hot face red heat sweat warm summer',
  '🥶': 'cold face blue freezing ice winter',
  '😱': 'face screaming fear scared shock gasp scream',
  '😨': 'fearful face scared afraid',
  '😰': 'anxious face sweat scared blue',
  '😥': 'sad relieved face sweat tear',
  '😓': 'downcast face sweat sad tired',
  '🤗': 'hugging face hug open hands',
  '🤔': 'thinking face think hmm ponder questioning',
  '🫣': 'peeking face peek hide cover eyes',
  '🤭': 'face hand mouth giggle oops whisper',
  '🫢': 'face open eyes hand mouth shock gasp oops',
  '🤫': 'shushing face quiet shh silence whisper',
  '🤥': 'lying face pinocchio long nose lie fib',
  '😶': 'face without mouth silent quiet empty',
  '😶‍🌫️': 'face in clouds fog lost confused hidden',
  '😐': 'neutral face poker face meh flat blank',
  '😑': 'expressionless face neutral flat bored',
  '😬': 'grimacing face grimace awkward tense teeth',
  '🫨': 'shaking face shock dizzy earthquake vibration',
  '🫠': 'melting face hot sarcasm warm disappear',
  '🙄': 'face rolling eyes sarcasm whatever bored annoyed',
  '😯': 'hushed face surprise gasp',
  '😦': 'frowning face open mouth sad surprise',
  '😧': 'anguished face pain shock',
  '😮': 'face open mouth wow surprise',
  '😲': 'astonished face shock surprise wow',
  '🥱': 'yawning face yawn tired sleepy',
  '😴': 'sleeping face zzz sleep snore tired',
  '🤤': 'drooling face drool saliva delicious tasty sleep',
  '😪': 'sleepy face tear bubble tired sleep',
  '😵': 'dizzy face dead faint cross eyes',
  '😵‍💫': 'face spiral eyes dizzy confused lost',
  '🤐': 'zipper-mouth face silent secret quiet zipper',
  '🥴': 'woozy face drunk tipsy dizzy uneven eyes',
  '🤢': 'nauseated face sick green vomit disgust',
  '🤮': 'face vomiting puke throw up sick disgust',
  '🤧': 'sneezing face sneeze cold flu blow nose tissue',
  '😷': 'face medical mask doctor sick protection nurse',
  '🤒': 'face thermometer sick temperature fever flu',
  '🤕': 'face head-bandage hurt accident bandage head',
  '🤑': 'money-mouth face cash rich dollar money green',
  '🤠': 'cowboy hat face sheriff country western hat',
  '😈': 'smiling face horns devil evil villain purple mischief',
  '👿': 'angry face horns devil evil villain angry purple',
  '👹': 'ogre monster red devil japanese folklore',
  '👺': 'goblin mask red long nose japanese drama devil',
  '🤡': 'clown face joker circus makeup funny',
  '💩': 'pile of poo poop turd smile brown',
  '👻': 'ghost spooky halloween scary float white',
  '💀': 'skull bone dead death skeleton head halloween',
  '☠️': 'skull crossbones danger poison pirate dead death',

  // Gestures
  '👋': 'waving hand wave hello hi goodbye bye',
  '🤚': 'raised back of hand',
  '🖐️': 'hand fingers splayed five',
  '✋': 'raised hand stop high five five',
  '🖖': 'vulcan salute spock live long prosper star trek',
  '👌': 'ok hand sign okay correct perfect nice',
  '🤌': 'pinched fingers italian hand gesture what do you want',
  '🤏': 'pinching hand small tiny little bit',
  '✌️': 'victory hand peace sign two',
  '🤞': 'crossed fingers luck hope wish',
  '🫰': 'hand index finger thumb crossed heart love korean finger heart',
  '🤟': 'love-you gesture hand sign love',
  '🤘': 'sign of the horns rock on heavy metal party',
  '🤙': 'call me hand phone gesture hang loose shaka',
  '👈': 'backhand index pointing left leftward directional',
  '👉': 'backhand index pointing right rightward directional',
  '👆': 'backhand index pointing up upward sky pointing',
  '🖕': 'middle finger insult rude flip off offensive',
  '👇': 'backhand index pointing down downward point down',
  '☝️': 'index pointing up point up first warning sky',
  '👍': 'thumbs up like yes agree good ok positive',
  '👎': 'thumbs down dislike no disagree bad negative',
  '✊': 'raised fist power strength protest',
  '👊': 'oncoming fist punch hit fight hello bump',
  '🤛': 'left-facing fist fist bump hello side',
  '🤜': 'right-facing fist fist bump hello side',
  '👏': 'clapping hands applause congrats bravo clap',
  '🙌': 'raising hands celebrate praise hooray',
  '👐': 'open hands hug welcome open',
  '🤲': 'palms up together pray beg book open hands',
  '🤝': 'handshake agreement shake hands deal partner business',
  '🙏': 'folded hands pray please thank you namaste hope',
  '✍️': 'writing hand write pen pencil note signature',
  '💅': 'nail polish manicure beauty fashion makeup cosmetic',
  '%)$': 'selfie',
  '🤳': 'selfie camera photo phone photograph picture',
  '💪': 'flexed biceps muscle strong power fitness workout gym',
  '🦾': 'mechanical arm robot prosthetic bionic',
  '🦿': 'mechanical leg robot prosthetic bionic',
  '狠': 'leg',
  '🦵': 'leg foot limb body physical',
  '🦶': 'foot toes step walk shoe path',
  '👂': 'ear listen hear sound audio',
  '🦻': 'ear hearing aid deaf hard of hearing accessibility',
  '👃': 'nose smell sniff scent body face',
  '🧠': 'brain mind intelligence smart think mental',
  '🫀': 'anatomical heart love medical organ organ cardiology',
  '🫁': 'lungs breath breathing health medical pulmonary organ',
  '🦷': 'tooth dentist teeth smile bone white health',
  '🦴': 'bone dog skeleton calcium white structure',
  '👀': 'eyes look see watch eye vision spy suspicious',
  '👁️': 'eye look see watch vision',
  '👅': 'tongue taste lick mouth talk speech',
  '👄': 'mouth lips talk kiss speech',
  '💋': 'kiss mark lipstick red lips print love makeup romance',
  '🩸': 'drop of blood blood bleed transfusion period red liquid',

  // People
  '👶': 'baby infant newborn kid toddler child',
  '👧': 'girl child kid female daughter young',
  '🧒': 'child kid toddler young',
  '👦': 'boy child kid male son young',
  '👩': 'woman adult female lady daughter mother wife sister',
  '🧑': 'person adult human individual',
  '👨': 'man adult male gentleman father husband brother son',
  '👩‍🦱': 'woman curly hair female curly',
  '🧑‍🦱': 'person curly hair curly',
  '👨‍🦱': 'man curly hair male curly',
  '👩‍🦰': 'woman red hair female ginger red',
  '🧑‍🦰': 'person red hair ginger red',
  '👨‍🦰': 'man red hair male ginger red',
  '👱‍♀️': 'blonde woman female blonde hair',
  '👱': 'blonde person blonde hair',
  '👱‍♂️': 'blonde man male blonde hair',
  '👩‍🦳': 'woman white hair female grey hair grandma',
  '🧑‍🦳': 'person white hair grey hair',
  '👨‍🦳': 'man white hair male grey hair grandpa',
  '👩‍🦲': 'woman bald female bald hairless',
  '🧑‍🦲': 'person bald bald hairless',
  '👨‍🦲': 'man bald male bald hairless',
  '👵': 'old woman grandma grandmother elderly elderly female',
  '🧓': 'older person senior elderly senior citizen',
  '👴': 'old man grandpa grandfather elderly elderly male',
  '👲': 'man cap skullcap hat chinese traditional',
  '👳‍♀️': 'woman wearing turban turban female sikh muslim',
  '👳': 'person wearing turban turban sikh',
  '👳‍♂️': 'man wearing turban turban male sikh muslim',
  '🧕': 'woman with headscarf hijab muslim islam arab female',
  '👮‍♀️': 'police officer woman cop police officer female security law enforcement',
  '👮': 'police officer cop patrol officer security guard law enforcement',
  '👮‍♂️': 'police officer man cop police officer male security law enforcement',
  '建造': 'construction worker',
  '👷‍♀️': 'construction worker woman engineer builder architect builder female helmet',
  '👷': 'construction worker builder architect engineer helmet safety',
  '👷‍♂️': 'construction worker man engineer builder architect builder male helmet',
  '💂‍♀️': 'guard woman royal guard queen british female guard',
  '💂': 'guard royal guard royal guard soldier uniform',
  '💂‍♂️': 'guard man royal guard king british male guard',
  '🕵️‍♀️': 'woman detective spy investigator inspector female spy magnifier magnifying',
  '🕵️': 'detective spy investigator inspector spy magnifier magnifying glass',
  '🕵️‍♂️': 'man detective spy investigator inspector male spy magnifier magnifying',
  '👩‍⚕️': 'woman health worker doctor nurse physician clinician female medicine',
  '🧑‍⚕️': 'health worker doctor nurse physician clinician medicine',
  '👨‍⚕️': 'man health worker doctor nurse physician clinician male medicine',
  '👩‍🌾': 'woman farmer farm agriculture farmer female countryside tractor',
  '🧑‍🌾': 'farmer farm agriculture countryside tractor',
  '👨‍🌾': 'man farmer farm agriculture farmer male countryside tractor',
  '👩‍🍳': 'woman cook chef baker cooking female restaurant kitchen apron',
  '🧑‍🍳': 'cook chef baker cooking restaurant kitchen apron',
  '👨‍🍳': 'man cook chef baker cooking male restaurant kitchen apron',
  '👩‍🎓': 'woman student graduate graduation graduation cap college university female study diploma',
  '🧑‍🎓': 'student graduate graduation graduation cap college university study diploma',
  '👨‍🎓': 'man student graduate graduation graduation cap college university male study diploma',
  '👩‍🎤': 'woman singer rockstar singer musician performer female rock pop star microphone',
  '🧑‍🎤': 'singer rockstar singer musician performer rock pop star microphone',
  '👨‍🎤': 'man singer rockstar singer musician performer male rock pop star microphone',
  '👩‍🏫': 'woman teacher educator instructor professor classroom female teaching school blackboard',
  '🧑‍🏫': 'teacher educator instructor professor classroom teaching school blackboard',
  '👨‍🏫': 'man teacher educator instructor professor classroom male teaching school blackboard',
  '👩‍🏭': 'woman factory worker welder manufacturer steel assembly female machine helmet',
  '🧑‍🏭': 'factory worker welder manufacturer steel assembly machine helmet',
  '👨‍🏭': 'man factory worker welder manufacturer steel assembly male machine helmet',
  '👩‍💻': 'woman technologist software programmer engineer coder developer laptop computer female tech',
  '🧑‍💻': 'technologist software programmer engineer coder developer laptop computer tech',
  '👨‍💻': 'man technologist software programmer engineer coder developer laptop computer male tech',
  '👩‍💼': 'woman office worker business manager executive company corporate employee office office female suit',
  '🧑‍💼': 'office worker business manager executive company corporate employee office office suit',
  '👨‍💼': 'man office worker business manager executive company corporate employee office office male suit',
  '👩‍🔧': 'woman mechanic plumber technician repair worker fix female wrench tools',
  '🧑‍🔧': 'mechanic plumber technician repair worker fix wrench tools',
  '👨‍🔧': 'man mechanic plumber technician repair worker fix male wrench tools',
  '👩‍🔬': 'woman scientist researcher chemist lab worker experiment lab laboratory female research test',
  '🧑‍🔬': 'scientist researcher chemist lab worker experiment lab laboratory research test',
  '👨‍🔬': 'man scientist researcher chemist lab worker experiment lab laboratory male research test',
  '👩‍调': 'artist',
  '👩‍🎨': 'woman artist painter designer drawing canvas palette paint creative art female',
  '🧑‍🎨': 'artist painter designer drawing canvas palette paint creative art',
  '👨‍🎨': 'man artist painter designer drawing canvas palette paint creative art male',
  '👩‍消': 'firefighter',
  '👩‍阻': 'firefighter',
  '👩‍🚒': 'woman firefighter fireman rescue emergency fire engine female helmet fire',
  '🧑‍🚒': 'firefighter fireman rescue emergency fire engine helmet fire',
  '👨‍🚒': 'man firefighter fireman rescue emergency fire engine male helmet fire',
  '👩‍✈️': 'woman pilot aviator flight captain airplane plane flight female pilot hat',
  '🧑‍✈️': 'pilot aviator flight captain airplane plane flight pilot hat',
  '👨‍✈️': 'man pilot aviator flight captain airplane plane flight male pilot hat',
  '👩‍🚀': 'woman astronaut space flight space explorer rocket nasa female helmet suit',
  '🧑‍🚀': 'astronaut space flight space explorer rocket nasa helmet suit',
  '👨‍🚀': 'man astronaut space flight space explorer rocket nasa male helmet suit',

  // Nature
  '🐶': 'dog face puppy pup pet animal bark woof',
  '🐱': 'cat face kitten kitty pet animal meow purr',
  '🐭': 'mouse face mouse rat rodent squeak pet',
  '🐹': 'hamster face hamster pet rodent cute',
  '🐰': 'rabbit face bunny rabbit pet ears carrot hopping',
  '🦊': 'fox face fox red fox wild animal forest',
  '🐻': 'bear face bear grizzly polar forest brown animal wild',
  '🐼': 'panda face panda bear bamboo china asian black and white',
  '🐻‍❄️': 'polar bear white bear arctic ice snow wild',
  '🐨': 'koala bear marsupial australia tree eucalyptus gray animal',
  '🐯': 'tiger face tiger cat striped wild feline orange power',
  '🦁': 'lion face lion king cat mane wild roar golden predator',
  '🐮': 'cow face cow cattle bull milk farm beef farm animal',
  '🐷': 'pig face pig pork oink farm animal pink snout',
  '🐽': 'pig nose pig snout pink smell',
  '🐸': 'frog face toad amphibian green croak pond hop',
  '🐵': 'monkey face monkey chimp ape forest banana jungle pet',
  '🙈': 'see-no-evil monkey hide cover eyes see no evil blindfold',
  '🙉': 'hear-no-evil monkey cover ears hear no evil deaf mute',
  '🙊': 'speak-no-evil monkey cover mouth speak no evil quiet secret',
  '🐒': 'monkey chimp ape climb tree banana jungle animal',
  '🐔': 'chicken hen rooster poultry bird egg farm cluck cock',
  '🐧': 'penguin bird flightless antarctic ice snow tux black and white',
  '🐦': 'bird avian flight wings chirp feather sky songbird',
  '🐤': 'baby chick bird young yellow chirp new',
  '🐣': 'hatching chick bird egg shell hatch birth newborn young yellow',
  '🐥': 'front-facing baby chick bird young yellow front chirp',
  '🦆': 'duck bird mallard quack pond feathers water',
  '🦅': 'eagle bird prey falcon hawk fly sky majestic freedom america',
  '🦉': 'owl bird nocturnal hoot wisdom forest eyes hunter predator',
  '🦇': 'bat mammal nocturnal flying vampire halloween cave wings',
  '🐺': 'wolf face wolf dog wild forest pack howl predator',
  '🐗': 'boar wild pig tusk forest mammal wild animal hog',
  '🐴': 'horse face horse pony farm stallion ride jockey equestrian gallop',
  '🦄': 'unicorn face unicorn horse horn magic fantasy fairytale rainbow',
  '🐝': 'honeybee bee insect honey sting yellow black stripes pollen wasp',
  '🪱': 'worm earthworm bug insect soil crawl earth pink',
  '🐛': 'bug caterpillar insect butterfly larva green cocoon crawl',
  '🦋': 'butterfly insect wings colorful moth flutter pretty fly',
  '🐌': 'snail mollusk shell slow crawl garden slime path',
  '🐞': 'lady beetle ladybug bug insect red spots garden good luck',
  '🐜': 'ant insect bug colony worker tiny crawl black',
  '🪰': 'fly housefly insect bug wings annoying dirty pest buzz',
  '🪲': 'beetle bug insect shell horn crawl green',
  '🪳': 'cockroach roach bug insect dirty pest crawl brown',
  '🦟': 'mosquito insect bug blood sting malaria disease wings buzz',
  '🦗': 'cricket grasshopper insect bug green jump sing chirp',
  '🕷️': 'spider arachnid insect bug eight legs web cobweb scary creep',
  '🕸️': 'spider web web cobweb spider house halloween net trap',
  '🦂': 'scorpion arachnid desert claws tail sting poison venom zodiac',
  '🐢': 'turtle tortoise reptile shell slow green sea pond pet',
  '🐍': 'snake serpent reptile crawl hiss venom poison scales zodiac',
  '🦎': 'lizard gecko reptile crawl green tail pet desert',
  '🦖': 't-rex tyrannosaurus rex dinosaur dino extinct jurassic monster predator',
  '🦕': 'sauropod brontosaurus dinosaur dino extinct giant herbivore green',
  '🐙': 'octopus sea ocean mollusk tentacles eight arms purple water',
  '🦑': 'squid sea ocean mollusk tentacles giant water ink',
  '🦐': 'shrimp prawn seafood crustacean pink ocean water delicious',
  '🦞': 'lobster seafood crustacean claws red ocean water delicious shell',
  '🦀': 'crab seafood crustacean claws red beach ocean water zodiac shell',
  '🐡': 'blowfish pufferfish fish ocean sea spikes round yellow water puffed',
  '🐠': 'tropical fish fish ocean sea colorful aquarium reef nemo',
  '🐟': 'fish sea ocean marine food swimming water blue gill',
  '🐬': 'dolphin sea ocean mammal jump swim smart friendly water',
  '🐳': 'spouting whale ocean sea whale blowing water giant blue mammal',
  '🐋': 'whale ocean sea whale giant blue mammal swimming water',
  '🦈': 'shark ocean sea predator teeth jaw swimming fin dangerous water',
  '🐊': 'crocodile alligator reptile swamp green jaws teeth predator reptile',
  '🐅': 'tiger striped cat wild feline animal orange predator',
  ' leopards': 'leopard',
  '🐆': 'leopard spotted cat wild feline cheetah jaguar predator spots',
  '🦓': 'zebra horse stripes African wild safari black and white',
  '🦍': 'gorilla ape chimp silverback monkey jungle primate strong black',
  '🦧': 'orangutan ape monkey red orange jungle primate borneo trees',
  '🦣': 'mammoth woolly elephant tusk ice age extinct furry giant',
  '🐘': 'elephant mammal tusk trunk gray safari africa india giant animal',

  // Food
  '🍇': 'grapes grape fruit purple vine wine vineyard',
  '🍈': 'melon cantaloupe honeydew fruit green sweet round',
  '🍉': 'watermelon fruit red green slice summer seeds juicy',
  '🍊': 'tangerine orange mandarin citrus fruit vitamin c sweet juice',
  '🍋': 'lemon citrus fruit yellow sour lemonade tart acid',
  '🍌': 'banana fruit yellow pool potassium monkey tropical',
  '🍍': 'pineapple fruit tropical crown sweet sour yellow juice',
  '🥭': 'mango fruit tropical orange sweet juice peach mango',
  '🍎': 'red apple fruit apple red sweet seed healthy teacher',
  '🍏': 'green apple fruit apple green sour healthy crisp',
  '🍐': 'pear fruit pear green sweet shape orchard juice',
  '🍑': 'peach fruit peach orange sweet fuzzy summer orchard',
  '🍒': 'cherries cherry fruit red pair sweet summer dessert',
  '🍓': 'strawberry fruit berry red seeds sweet summer dessert jam',
  '🫐': 'blueberries blueberry fruit berry blue sweet healthy dessert',
  '🥝': 'kiwifruit kiwi fruit green brown fuzzy vitamin c sweet slice',
  '🍅': 'tomato vegetable red fruit salad ketchup pizza sauce garden',
  '🫒': 'olive green olive oil pizza greek martini branch peace',
  '🥥': 'coconut fruit tropical brown hard milk water palm tree',
  '🥑': 'avocado green fruit seed guacamole healthy toast fat superfood',
  '🍆': 'eggplant aubergine vegetable purple veggie',
  '🥔': 'potato vegetable tuber starch french fries potato mash brown',
  '🥕': 'carrot vegetable orange root rabbit beta carotene healthy sweet',
  '🌽': 'ear of corn maize sweetcorn vegetable yellow cob farm pop',
  '🌶️': 'hot pepper chili chilli hot spicy red taco mexican spice',
  '🫑': 'bell pepper pepper capsicum vegetable green sweet red yellow',
  '🧅': 'onion vegetable bulb white purple cry spice cook ingredient',
  '🧄': 'garlic bulb spice cook smell white clove ingredient herb',
  '🫚': 'ginger root spice cook tea asian yellow root ingredient',
  '🫛': 'pea pod peas vegetable green pod healthy seed',
  '🥦': 'broccoli vegetable green tree healthy veggie florets',
  '🍄': 'mushroom fungus forest toadstool pizza soup red cap',
  '🥜': 'peanuts peanut nut seed snack butter shell salty groundnut',
  '🫘': 'beans kidney bean legume bean chili seed healthy protein',
  '🌰': 'chestnut nut roasted brown forest autumn fall',
  '🍞': 'bread loaf slice bakery toast wheat flour carb yeast',
  '🥐': 'croissant bread French pastry bakery buttery crescent roll',
  '🥖': 'baguette bread French bread loaf bakery long crusty sandwich',
  '🫓': 'flatbread pita naan tortilla bread wrap bakery round',
  '🥨': 'pretzel snack twist salty bakery German twist',
  '🥯': 'bagel bread bakery round hole cream cheese breakfast',
  '🥞': 'pancakes hotcake breakfast sweet butter maple syrup stack',
  '🧇': 'waffle grid breakfast sweet butter syrup toaster grid',
  '🧀': 'cheese wedge yellow swiss dairy cheddar pizza mouse holes',
  '🍖': 'meat on bone meat bone ham pork beef caveman steak rib',
  '🍗': 'poultry leg chicken drumstick turkey meat fried farm roast',
  '🥩': 'cut of meat steak beef raw marbled grill bbq barbecue beefsteak',
  '🌭': 'hot dog hotdog sausage bun mustard fast food baseball street',
  '🍔': 'hamburger burger cheeseburger fast food beef cheese patty sesame',
  '🍟': 'french fries fries potato fast food potato chips salty red',
  '🍕': 'pizza slice cheese pepperoni italian fast food tomato dough slice',
  '🥪': 'sandwich bread ham cheese lettuce lunch picnic deli bread',
  '🌮': 'taco mexican food shell beef lettuce cheese tortilla fast food',
  '🌯': 'burrito mexican food wrap tortilla beef rice beans cheese wrap',
  '🍳': 'cooking egg fried pan breakfast fry yolk sunny side up skillet',
  '🥗': 'green salad bowl lettuce tomato cucumber healthy vegetables veggie salad bowl',
  '🍿': 'popcorn bucket snack movie cinema theater corn salt butter striped',
  '🧈': 'butter stick dairy fat cooking spread toast yellow block slice',
  '🧂': 'salt shaker spice season sodium white pour food bottle',
  '🥫': 'canned food tin can preserve sauce soup container pantry label',
  '🍱': 'bento box japanese lunch box rice sushi vegetables container partition',
  '🍚': 'cooked rice bowl white rice grains asian food bowl chopsticks',
  '🍛': 'curry and rice indian food spicy gravy bowl yellow sauce rice',
  '🍣': 'sushi roll maki salmon rice seaweed japanese chopsticks raw fish',
  '🍤': 'fried shrimp tempura seafood crunchy fried golden ebi',
  '🍡': 'dango sweet dumpling skewer japanese dessert pink green white round',
  '🥟': 'dumpling gyoza potsticker asian food dim sum dough wrapper meat veggie',
  '🥠': 'fortune cookie chinese restaurant prediction paper luck sweet fold',
  '🥡': 'takeout box chinese food delivery container box wire handle paper',
  '🍦': 'soft ice cream cone soft serve dairy sweet dessert chocolate vanilla swirl',
  '🍧': 'shaved ice dessert cone syrup colorful summer cool ice cup',
  '🍰': 'birthday cake cake slice sweet dessert candle celebrate party strawberry',
  '🧁': 'cupcake sweet muffin frosting cherry dessert bakery cup',
  '🥧': 'pie slice dessert sweet fruit pumpkin apple baking crust slice',
  '🍫': 'chocolate bar sweet candy cocoa brown wrap foil milk',
  '🍬': 'candy sweet wrapped colorful sugar treat kid halloween',
  '🍭': 'lollipop candy sweet sucker pop stick round swirl red sugar',

  // Activities
  '👾': 'alien monster retro video game space invader arcade pixel pixelart',
  '⚽': 'soccer ball football sports game play kick goal match',
  '🏀': 'basketball sports ball game hoop bounce orange play',
  '🏈': 'american football rugby sports ball brown oval yard pigskin play',
  '⚾': 'baseball sports ball glove bat home run white red stitching play',
  '🥎': 'softball sports ball game play yellow large baseball',
  '🎾': 'tennis racket ball sports game net green court play',
  '🏐': 'volleyball sports ball game net beach sand court play',
  '🏉': 'rugby union football sports ball game play oval pass scrum',
  '🥏': 'flying disc frisbee sports toy throw catch beach dog game',
  '🎱': 'billiards pool 8 ball black game table cue stick pocket pool',
  '🪀': 'yo-yo toy spin string up down retro kid game',
  '🏓': 'ping pong table tennis paddle ball game net play sports',
  '🏸': 'badminton racket shuttlecock birdie sports game net court play',
  '🏒': 'ice hockey stick puck game net ice rink skater play sports',
  '🏑': 'field hockey stick ball sports game grass turf play',
  '🥍': 'lacrosse stick pocket net ball sports game play team helmet',
  '🏏': 'cricket bat ball wickets sports game bowler batsman runs play',
  '🪃': 'boomerang throw catch return wood hunting australia weapon toy',
  '🥅': 'goal net soccer hockey sports target keeper score mesh',
  '⛳': 'flag in hole golf ball club green course putt drive sports',
  '🪁': 'kite fly sky wings string wind toy fun park wind',
  '🏹': 'bow and arrow archer archery target bow arrow shoot sports',
  '🎣': 'fishing pole fish hook water river lake bait catch reel sport',
  '🤿': 'diving mask snorkel scuba goggles swim swim sea ocean under water goggles',
  '🥊': 'boxing glove box fight punch boxer sports red match fighter',
  '🥋': 'martial arts uniform karate judo taekwondo gi belt black belt combat sport',
  '🎽': 'running shirt sash track field sports singlet uniform race run',
  '🛹': 'skateboard skate board wheels ride skatepark roll deck sports',
  '🛼': 'roller skate skates quad wheels roll rink retro sports',
  '🛷': 'sled bobsled luge winter snow ride ice downhill sliding',
  '⛸️': 'ice skate skates ice rink figure skating winter sports blade',
  '🥌': 'curling stone broom ice winter game olympics slide rock',
  '💡': 'light bulb idea electricity bright',
  '🎿': 'skis ski poles snow winter mountain slope downhill skiing sports',
  '高度': 'skier',
  '⛷️': 'skier ski snow winter mountain slope downhill speed sport',
  '🏂': 'snowboarder snowboard snow winter mountain slope ride freestyle sport',
  '🏋️‍♀️': 'woman lifting weights weightlifter weight gym workout fitness strong barbell female',
  '🏋️': 'person lifting weights weightlifter gym workout fitness strong barbell lift',
  '🏋️‍♂️': 'man lifting weights weightlifter weight gym workout fitness strong barbell male',
  '🤺': 'fencer fencing sword sport blade mask foil epee combat foil',
  '🤼‍♀️': 'women wrestling wrestlers ring fight combat mat sport female wrestling',
  '🤼': 'people wrestling wrestlers ring fight combat mat sport wrestling',
  '🤼‍♂️': 'men wrestling wrestlers ring fight combat mat sport male wrestling',
  '🤸‍♀️': 'woman cartwheeling gymnastics acrobat balance gym mat female cartwheel',
  '🤸': 'person cartwheeling gymnastics acrobat balance gym mat cartwheel',
  '🤸‍♂️': 'man cartwheeling gymnastics acrobat balance gym mat male cartwheel',
  '⛹️‍♀️': 'woman bouncing ball basketball sports player court dribble female dribbling',
  '⛹️': 'person bouncing ball basketball sports player court dribble dribbling',
  '⛹️‍♂️': 'man bouncing ball basketball sports player court dribble male dribbling',
  '🤾‍♀️': 'woman playing handball sports player team throw goal court female handball',
  '🤾': 'person playing handball sports player team throw goal court handball',
  '🤾‍♂️': 'man playing handball sports player team throw goal court male handball',
  '🧗‍♀️': 'woman climbing rock climber mountain wall indoor gym harness female climb',
  '🧗': 'person climbing rock climber mountain wall indoor gym harness climb',
  '🧗‍♂️': 'man climbing rock climber mountain wall indoor gym harness male climb',
  '🚴‍♀️': 'woman biking cyclist bicycle bike ride road helmet race female cycling',
  '🚴': 'person biking cyclist bicycle bike ride road helmet race cycling',
  '🚴‍♂️': 'man biking cyclist bicycle bike ride road helmet race male cycling',
  '🚵‍♀️': 'woman mountain biking cyclist bicycle bike trail mountain dirt female cycling',
  '🚵': 'person mountain biking cyclist bicycle bike trail mountain dirt cycling',

  // Objects
  '🔦': 'flashlight torch light beam battery search dark night',
  '🕯️': 'candle wax flame light melt burn wax smell fire lighting',
  '🪔': 'diya lamp clay oil wick hindu diwali festival light deepavali',
  '🗑️': 'wastebasket trash can dustbin garbage rubbish waste basket container',
  '🛢️': 'oil drum barrel petroleum fuel chemical container container',
  '💸': 'money with wings flying cash spend bills wealth lose loss cash',
  '💵': 'dollar bill cash paper money currency bank green note bills',
  '💴': 'yen bill cash paper money currency japan bank note bills',
  '存放': 'euro bill',
  '💶': 'euro bill cash paper money currency europe bank note bills',
  '💷': 'pound bill cash paper money currency uk bank note bills',
  '🪙': 'coin cash metal currency cents gold silver change money',
  '💰': 'money bag cash bag gold wealth bank rich dollar cash bag',
  '💳': 'credit card debit card payment visa bank plastic card wallet money',
  '💎': 'gem stone diamond jewelry precious crystal blue ring luxury wealth',
  '⚖️': 'balance scale justice law court attorney judge weights equal',
  '🪜': 'ladder climb step reach height roof construction tools repair',
  '🔧': 'wrench spanner tools repair mechanic plumber bolt nut adjust tool',
  '🔨': 'hammer tools repair nail build hit construction tool mallet',
  '⚒️': 'hammer and pick tools mining construction metalwork tool',
  '🛠️': 'hammer and wrench tools repair fix build diy tools',
  '⛏️': 'pick mining tools pickaxe rock coal dig tool',
  '💾': 'floppy disk diskette save storage record computer data technology',
  '💿': 'optical disk cd dvd music movie record disc technology computer',
  '📀': 'dvd optical disk movie music record disc technology computer',
  '📱': 'mobile phone smartphone telephone cell call screen touch technology',
  '📲': 'mobile phone arrow incoming call notification cell telephone technology',
  '💻': 'laptop computer notebook monitor keyboard screen work pc office technology',
  '⌨️': 'keyboard computer input keys type write technology office',
  '🖥️': 'desktop computer monitor screen pc technology office work',
  '🖨️': 'printer print paper document ink copy machine office machine',
  '🖱️': 'computer mouse click cursor scroll navigate select computer device',
  '🖲️': 'trackball mouse ball click cursor scroll navigate computer device',
  '🕹️': 'joystick game controller arcade play video game retro computer device',
  '🗜️': 'clamp vise tool garage workshop hold press industrial tool',
  '📼': 'videocassette vhs tape movie record play retro technology player',
  '📷': 'camera photo photograph lens picture shoot technology device',
  '📸': 'camera flash photo photograph picture lens shoot device light',
  '📹': 'video camera camcorder movie record video film tape device',
  '🎥': 'movie camera cinema film theater project record hollywood movie',
  '📽️': 'film projector movie cinema slides show light lens retro movie',
  '🎞️': 'film frames negative strip movie photo camera retro film',
  '📞': 'telephone receiver handset phone call speak listen talk device',
  '☎️': 'telephone phone landline dial call office home speak talk',
  '📟': 'pager beeper call messaging alert retro communication device',
  '📠': 'fax machine printer phone copy send doc document office machine',
  '电视': 'television',
  '📺': 'television tv screen show broadcast program retro cabinet device',
  '📻': 'radio broadcast receiver music tune fm am antenna device',
  '🎙️': 'studio microphone mic record music song voice audio podcast stand',
  '🎚️': 'level slider volume equalizer mix control fader panel',
  '🎛️': 'control knobs volume equalizer mix control dials panel',
  '🧭': 'compass direction north south east west navigate map explore hike',
  '⏱️': 'stopwatch timer clock sport time race second countdown dial',
  '⏲️': 'timer clock kitchen egg timer cook countdown alarm dial',
  '⏰': 'alarm clock clock wake sleep morning time alert ring dial',
  '⌛': 'hourglass time sand flow wait end history antique clock',
  '⏳': 'hourglass sand running time flow wait progress antique clock',
  '📡': 'satellite dish antenna radar space beam receiver signal transmission communication',
  '⌚': 'watch wrist watch time clock smart watch wearable wrist',

  // Symbols
  '💘': 'heart with arrow cupid love valentines shoot bow pink romantic',
  '💝': 'heart with ribbon gift present valentine love bow pink wrap',
  '💖': 'sparkling heart pink love heart sparkle shine pretty glow',
  '💗': 'growing heart pink love heart grow beat pulse size',
  '💓': 'beating heart pink love heart beat pulse vibration line',
  '💞': 'revolving hearts pink love hearts circle spin rotate around',
  '💕': 'two hearts pink love hearts double pair companion',
  '💟': 'heart decoration pink love heart frame square purple white',
  '❣️': 'heart exclamation heart mark red love warning dot mark symbol',
  '💔': 'broken heart red love break apart hurt sad divorce separation',
  '❤️‍🔥': 'heart on fire red love fire flame burn hot passion desire',
  '❤️‍🩹': 'mending heart red love bandage cure heal hurt recover',
  '❤️': 'red heart love like adore favorite romantic red',
  '🩷': 'pink heart love like adore favorite sweet cute pink',
  '🧡': 'orange heart love like orange',
  '💛': 'yellow heart love like friendship warm yellow',
  '💚': 'green heart love like env green jealousy nature',
  '💙': 'blue heart love like trust blue peace loyalty',
  '🩵': 'light blue heart love like trust peace sky turquoise',
  '💜': 'purple heart love like respect purple luxury royalty honour',
  '🤎': 'brown heart love like brown earth wood chocolate solid',
  '🖤': 'black heart love like dark black grief gothic emo evil',
  '🩶': 'grey heart love like grey silver new neutral dull modern',
  '🤍': 'white heart love like pure white clean peace light respect',
  '💯': 'hundred points 100 percent perfect A grade test exam score absolute',
  '💢': 'anger symbol comic angry mad red vein cross popping punch line',
  '💥': 'collision boom explosion bang spark flash hit clash orange',
  '💫': 'dizzy star spark circle spin rotate yellow stars magic spark',
  '💦': 'sweat droplets water splash drop wet moisture clean rain wash',
  '💨': 'dashing away puff wind run escape dust smoke fast speed motion',
  '🕳️': 'hole black circle pit ground deep dark drop trap empty empty space',
  '💣': 'bomb weapon fuse spark explosion blow up dangerous black steel pirate',
  '💬': 'speech balloon talk bubble chat speak message comment text word conversation',
  '👁️‍🗨️': 'eye in speech bubble speech balloon eye witness anti bullying symbol campaign watch',
  '🗨️': 'left speech balloon talk bubble chat message comment text conversation',
  '🗯️': 'right anger bubble angry talk scream shout conversation text comic',
  '💭': 'thought balloon think bubble dream idea head wonder mind cloud',
  '💤': 'zzz sleep snoring tired dream bed night dark sleep sign rest',
  '🌐': 'globe with meridians world earth internet network global web lines blue',
  '🌀': 'cyclone spiral hurricane vortex twister storm wind blue spinning',
  '☮️': 'peace symbol circle lines peace sign harmony violet white',
  '🕉️': 'om symbol hindu hinduism yoga meditation spirituality sacred violet',
  '☸️': 'wheel of dharma buddhism path law rotation religion violet gold',
  '🔯': 'six pointed star dotted hexagram star star of david dot center religion star'
}

export function matchEmoji(emoji: string, query: string): boolean {
  const cleanQuery = query.toLowerCase().trim()
  if (!cleanQuery) return true

  // Direct match
  if (emoji === cleanQuery) return true

  // Keyword match
  const keywords = EMOJI_KEYWORDS_MAP[emoji]
  if (keywords && keywords.toLowerCase().includes(cleanQuery)) {
    return true
  }

  return false
}
