const fs = require('fs');
const path = require('path');
const ts = require('typescript');

const srcDir = path.join(__dirname, '../src');
const outputFilePath = path.join(srcDir, 'main/extensions/docs/generatedDocs.ts');

console.log('[Generate Docs] Starting TypeScript compiler AST-based API extraction...');

function parseTypeScriptFile(filePath) {
  const fileContent = fs.readFileSync(filePath, 'utf8');
  const sourceFile = ts.createSourceFile(filePath, fileContent, ts.ScriptTarget.Latest, true);
  
  const defs = {};
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });

  function visit(node) {
    if (ts.isInterfaceDeclaration(node)) {
      const isExported = node.modifiers && node.modifiers.some(m => m.kind === ts.SyntaxKind.ExportKeyword);
      if (isExported) {
        const name = node.name.text;
        let text = printer.printNode(ts.EmitHint.Unspecified, node, sourceFile);
        // Clean up 'export ' from the generated docs output to make it cleaner for developers
        text = text.replace(/^export\s+/, '');
        defs[name] = text;
      }
    } else if (ts.isTypeAliasDeclaration(node)) {
      const isExported = node.modifiers && node.modifiers.some(m => m.kind === ts.SyntaxKind.ExportKeyword);
      if (isExported) {
        const name = node.name.text;
        let text = printer.printNode(ts.EmitHint.Unspecified, node, sourceFile);
        text = text.replace(/^export\s+/, '');
        defs[name] = text;
      }
    }
    ts.forEachChild(node, visit);
  }

  visit(sourceFile);
  return { defs, sourceFile };
}

try {
  const contextPath = path.join(srcDir, 'main/extensions/context/ExtensionContext.ts');
  const eventMapPath = path.join(srcDir, 'main/extensions/context/ExtensionEventMap.ts');
  const ipcMessagePath = path.join(srcDir, 'main/ipc/message.types.ts');
  const manifestPath = path.join(srcDir, 'main/extensions/types/ExtensionManifest.ts');

  const { defs: contextDefs } = parseTypeScriptFile(contextPath);
  const { defs: eventMapDefs, sourceFile: eventMapSourceFile } = parseTypeScriptFile(eventMapPath);
  const { defs: ipcMessageDefs } = parseTypeScriptFile(ipcMessagePath);
  const { defs: manifestDefs } = parseTypeScriptFile(manifestPath);

  // Parse the event map to extract mapped events
  const events = [];
  function extractEvents(node) {
    if (ts.isInterfaceDeclaration(node) && node.name.text === 'ExtensionEventMap') {
      for (const member of node.members) {
        if (ts.isPropertySignature(member)) {
          const eventName = (member.name.text || member.name.getText(eventMapSourceFile)).replace(/['"]/g, '');
          const payloadInterface = member.type.getText(eventMapSourceFile);
          
          let payloadDef = eventMapDefs[payloadInterface] || ipcMessageDefs[payloadInterface] || 'unknown';
          events.push({
            name: eventName,
            payloadInterface,
            payloadDef
          });
        }
      }
    }
    ts.forEachChild(node, extractEvents);
  }
  extractEvents(eventMapSourceFile);

  // Combine all definitions
  const allDefs = {
    ...contextDefs,
    ...eventMapDefs,
    ...ipcMessageDefs,
    ...manifestDefs
  };

  const outputContent = `// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
// Generated on: ${new Date().toISOString()}
// Run "node scripts/generate-docs.js" to regenerate.

export const GENERATED_INTERFACES: Record<string, string> = ${JSON.stringify(allDefs, null, 2)};

export interface GeneratedEventInfo {
  name: string;
  payloadInterface: string;
  payloadDef: string;
}

export const GENERATED_EVENTS: GeneratedEventInfo[] = ${JSON.stringify(events, null, 2)};
`;

  const outputDir = path.dirname(outputFilePath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputFilePath, outputContent, 'utf8');
  console.log('[Generate Docs] API documentation successfully generated using TypeScript compiler API!');
} catch (error) {
  console.error('[Generate Docs] Failed to extract API documentation:', error);
  process.exit(1);
}
