// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
// Generated on: 2026-07-20T11:14:46.365Z
// Run "node scripts/generate-docs.js" to regenerate.

export const GENERATED_INTERFACES: Record<string, string> = {
  "IExtensionEventAPI": "interface IExtensionEventAPI {\n    on<K extends ExtensionEventName>(event: K, handler: (payload: ExtensionEventMap[K]) => void | Promise<void>): () => void;\n}",
  "IExtensionLogAPI": "interface IExtensionLogAPI {\n    info(msg: string, ...data: any[]): void;\n    warn(msg: string, ...data: any[]): void;\n    error(msg: string, ...data: any[]): void;\n}",
  "IExtensionStorageAPI": "interface IExtensionStorageAPI {\n    get<T = unknown>(key: string): Promise<T | undefined>;\n    set(key: string, value: unknown): Promise<void>;\n    delete(key: string): Promise<void>;\n    clear(): Promise<void>;\n    keys(): Promise<string[]>;\n}",
  "IExtensionSchedulerAPI": "interface IExtensionSchedulerAPI {\n    setInterval(ms: number, fn: () => void | Promise<void>): () => void;\n    setTimeout(ms: number, fn: () => void | Promise<void>): () => void;\n    onCron(name: string, fn: () => void | Promise<void>): void;\n}",
  "ToolResult": "interface ToolResult {\n    text: string;\n}",
  "ExtensionTool": "interface ExtensionTool {\n    name: string;\n    description: string;\n    schema: object;\n    execute: (args: Record<string, unknown>) => Promise<ToolResult>;\n}",
  "IExtensionToolCallAPI": "interface IExtensionToolCallAPI {\n    call(toolName: string, args: Record<string, unknown>): Promise<ToolResult>;\n    list(): string[];\n}",
  "IExtensionToolRegisterAPI": "interface IExtensionToolRegisterAPI {\n    register(tool: ExtensionTool): void;\n    list(): string[];\n}",
  "IExtensionToolAPI": "type IExtensionToolAPI = Partial<IExtensionToolCallAPI & IExtensionToolRegisterAPI>;",
  "NotifyAction": "interface NotifyAction {\n    id: string;\n    title: string;\n}",
  "DedicatedChatMessage": "interface DedicatedChatMessage {\n    id: string;\n    extensionId: string;\n    role: 'user' | 'extension';\n    content: string | any;\n    createdAt: Date;\n}",
  "DedicatedChatContent": "interface DedicatedChatContent {\n    type: 'text' | 'card';\n    text?: string;\n    title?: string;\n    body?: string;\n    buttons?: Array<{\n        id: string;\n        label: string;\n    }>;\n}",
  "IExtensionDedicatedChatAPI": "interface IExtensionDedicatedChatAPI {\n    send(content: DedicatedChatContent): Promise<void>;\n    getHistory(limit?: number): Promise<DedicatedChatMessage[]>;\n    clearHistory(): Promise<void>;\n    focus(): void;\n}",
  "IExtensionUIAPI": "interface IExtensionUIAPI {\n    notify(opts: {\n        title: string;\n        body: string;\n        action?: NotifyAction;\n    }): Promise<void>;\n    toast(msg: string, level?: 'info' | 'success' | 'warning' | 'error'): void;\n    showSettings(schema: object): Promise<Record<string, unknown>>;\n}",
  "ExtensionContext": "interface ExtensionContext {\n    readonly extensionId: string;\n    readonly manifest: ExtensionManifest;\n    readonly log: IExtensionLogAPI;\n    onActivate(fn: () => Promise<void>): void;\n    onDeactivate(fn: () => Promise<void>): void;\n    readonly storage?: IExtensionStorageAPI;\n    readonly events?: IExtensionEventAPI;\n    readonly scheduler?: IExtensionSchedulerAPI;\n    readonly tools?: IExtensionToolAPI;\n    readonly ui?: IExtensionUIAPI;\n    readonly dedicatedChat?: IExtensionDedicatedChatAPI;\n}",
  "ExtensionMessageIncomingEvent": "interface ExtensionMessageIncomingEvent {\n    chatJid: string;\n    senderJid: string;\n    textContent: string | null;\n    fromMe: boolean;\n    timestamp: bigint;\n    enriched: EnrichedMessage;\n}",
  "ExtensionMessageDeletedEvent": "interface ExtensionMessageDeletedEvent {\n    messageId: string;\n    chatJid: string;\n    fromMe: boolean;\n}",
  "ExtensionMessageEditedEvent": "interface ExtensionMessageEditedEvent {\n    messageId: string;\n    chatJid: string;\n    fromMe: boolean;\n    participant: string | null;\n    editedTextContent: string | null;\n}",
  "ExtensionMessageStatusUpdatedEvent": "interface ExtensionMessageStatusUpdatedEvent {\n    id: string;\n    chatJid: string;\n    status: string;\n}",
  "ExtensionReactionProcessedEvent": "interface ExtensionReactionProcessedEvent {\n    id: string;\n    chatJid: string;\n    remoteJid: string;\n    fromMe: boolean;\n    senderId: number | null;\n    participant: string;\n    participantName: string;\n    timestamp: string;\n    messageType: 'reactionMessage';\n    targetMessageType?: string;\n    targetTextContent?: string | null;\n    content: string;\n}",
  "ExtensionChatCreatedEvent": "interface ExtensionChatCreatedEvent {\n    jid: string;\n    name?: string;\n}",
  "ExtensionChatArchivedEvent": "interface ExtensionChatArchivedEvent {\n    jid: string;\n    archived: boolean;\n}",
  "ExtensionChatPinnedEvent": "interface ExtensionChatPinnedEvent {\n    jid: string;\n    pinned: boolean;\n}",
  "ExtensionContactUpdatedEvent": "interface ExtensionContactUpdatedEvent {\n    jid: string;\n    name?: string;\n    pushName?: string;\n}",
  "ExtensionGroupParticipantAddedEvent": "interface ExtensionGroupParticipantAddedEvent {\n    id: string;\n    participants: string[];\n}",
  "ExtensionGroupParticipantRemovedEvent": "interface ExtensionGroupParticipantRemovedEvent {\n    id: string;\n    participants: string[];\n}",
  "ExtensionGroupSubjectChangedEvent": "interface ExtensionGroupSubjectChangedEvent {\n    id: string;\n    subject: string;\n}",
  "ExtensionConnectionOpenEvent": "interface ExtensionConnectionOpenEvent {\n}",
  "ExtensionConnectionCloseEvent": "interface ExtensionConnectionCloseEvent {\n}",
  "ExtensionDedicatedChatMessageEvent": "interface ExtensionDedicatedChatMessageEvent {\n    text: string;\n}",
  "ExtensionEventMap": "interface ExtensionEventMap {\n    'message:incoming': ExtensionMessageIncomingEvent;\n    'message:deleted': ExtensionMessageDeletedEvent;\n    'message:edited': ExtensionMessageEditedEvent;\n    'message:status-updated': ExtensionMessageStatusUpdatedEvent;\n    'reaction:processed': ExtensionReactionProcessedEvent;\n    'chat:created': ExtensionChatCreatedEvent;\n    'chat:archived': ExtensionChatArchivedEvent;\n    'chat:pinned': ExtensionChatPinnedEvent;\n    'contact:updated': ExtensionContactUpdatedEvent;\n    'group:participant-added': ExtensionGroupParticipantAddedEvent;\n    'group:participant-removed': ExtensionGroupParticipantRemovedEvent;\n    'group:subject-changed': ExtensionGroupSubjectChangedEvent;\n    'connection:open': ExtensionConnectionOpenEvent;\n    'connection:close': ExtensionConnectionCloseEvent;\n    'extension:chat-message': ExtensionDedicatedChatMessageEvent;\n}",
  "ExtensionEventName": "type ExtensionEventName = keyof ExtensionEventMap;",
  "EnrichedMessage": "/** Enriched message returned to the frontend via IPC. */\nexport interface EnrichedMessage {\n    id: string;\n    chatJid: string;\n    fromMe: boolean;\n    participant: string | null;\n    participantName: string;\n    timestamp: string;\n    messageType: string;\n    content: string;\n    reactions?: EnrichedReaction[];\n    isDeleted?: boolean;\n    isEdited?: boolean;\n    status?: string | null;\n}",
  "SlashCommand": "interface SlashCommand {\n    name: string;\n    description: string;\n}",
  "CronEntry": "interface CronEntry {\n    name: string;\n    cron: string;\n}",
  "ExtensionManifest": "interface ExtensionManifest {\n    id: string;\n    version: string;\n    apiVersion: string;\n    name: string;\n    description: string;\n    main: string;\n    permissions: string[];\n    dedicatedChat?: {\n        name: string;\n        avatarEmoji: string;\n        commands: SlashCommand[];\n    };\n    scheduler?: {\n        onStart: boolean;\n        intervals: CronEntry[];\n    };\n}"
};

export interface GeneratedEventInfo {
  name: string;
  payloadInterface: string;
  payloadDef: string;
}

export const GENERATED_EVENTS: GeneratedEventInfo[] = [
  {
    "name": "message:incoming",
    "payloadInterface": "ExtensionMessageIncomingEvent",
    "payloadDef": "interface ExtensionMessageIncomingEvent {\n    chatJid: string;\n    senderJid: string;\n    textContent: string | null;\n    fromMe: boolean;\n    timestamp: bigint;\n    enriched: EnrichedMessage;\n}"
  },
  {
    "name": "message:deleted",
    "payloadInterface": "ExtensionMessageDeletedEvent",
    "payloadDef": "interface ExtensionMessageDeletedEvent {\n    messageId: string;\n    chatJid: string;\n    fromMe: boolean;\n}"
  },
  {
    "name": "message:edited",
    "payloadInterface": "ExtensionMessageEditedEvent",
    "payloadDef": "interface ExtensionMessageEditedEvent {\n    messageId: string;\n    chatJid: string;\n    fromMe: boolean;\n    participant: string | null;\n    editedTextContent: string | null;\n}"
  },
  {
    "name": "message:status-updated",
    "payloadInterface": "ExtensionMessageStatusUpdatedEvent",
    "payloadDef": "interface ExtensionMessageStatusUpdatedEvent {\n    id: string;\n    chatJid: string;\n    status: string;\n}"
  },
  {
    "name": "reaction:processed",
    "payloadInterface": "ExtensionReactionProcessedEvent",
    "payloadDef": "interface ExtensionReactionProcessedEvent {\n    id: string;\n    chatJid: string;\n    remoteJid: string;\n    fromMe: boolean;\n    senderId: number | null;\n    participant: string;\n    participantName: string;\n    timestamp: string;\n    messageType: 'reactionMessage';\n    targetMessageType?: string;\n    targetTextContent?: string | null;\n    content: string;\n}"
  },
  {
    "name": "chat:created",
    "payloadInterface": "ExtensionChatCreatedEvent",
    "payloadDef": "interface ExtensionChatCreatedEvent {\n    jid: string;\n    name?: string;\n}"
  },
  {
    "name": "chat:archived",
    "payloadInterface": "ExtensionChatArchivedEvent",
    "payloadDef": "interface ExtensionChatArchivedEvent {\n    jid: string;\n    archived: boolean;\n}"
  },
  {
    "name": "chat:pinned",
    "payloadInterface": "ExtensionChatPinnedEvent",
    "payloadDef": "interface ExtensionChatPinnedEvent {\n    jid: string;\n    pinned: boolean;\n}"
  },
  {
    "name": "contact:updated",
    "payloadInterface": "ExtensionContactUpdatedEvent",
    "payloadDef": "interface ExtensionContactUpdatedEvent {\n    jid: string;\n    name?: string;\n    pushName?: string;\n}"
  },
  {
    "name": "group:participant-added",
    "payloadInterface": "ExtensionGroupParticipantAddedEvent",
    "payloadDef": "interface ExtensionGroupParticipantAddedEvent {\n    id: string;\n    participants: string[];\n}"
  },
  {
    "name": "group:participant-removed",
    "payloadInterface": "ExtensionGroupParticipantRemovedEvent",
    "payloadDef": "interface ExtensionGroupParticipantRemovedEvent {\n    id: string;\n    participants: string[];\n}"
  },
  {
    "name": "group:subject-changed",
    "payloadInterface": "ExtensionGroupSubjectChangedEvent",
    "payloadDef": "interface ExtensionGroupSubjectChangedEvent {\n    id: string;\n    subject: string;\n}"
  },
  {
    "name": "connection:open",
    "payloadInterface": "ExtensionConnectionOpenEvent",
    "payloadDef": "interface ExtensionConnectionOpenEvent {\n}"
  },
  {
    "name": "connection:close",
    "payloadInterface": "ExtensionConnectionCloseEvent",
    "payloadDef": "interface ExtensionConnectionCloseEvent {\n}"
  },
  {
    "name": "extension:chat-message",
    "payloadInterface": "ExtensionDedicatedChatMessageEvent",
    "payloadDef": "interface ExtensionDedicatedChatMessageEvent {\n    text: string;\n}"
  }
];
