export type { ReactionItem, MessageItem, MessageReceiptInfo } from '../../../shared/ipc/dto'

export type MessageType =
  | 'stickerMessage'
  | 'lottieStickerMessage'
  | 'imageMessage'
  | 'videoMessage'
  | 'ptvMessage'
  | 'documentMessage'
  | 'audioMessage'
  | 'conversation'
  | 'extendedTextMessage'
  | 'templateMessage'
  | 'reactionMessage'
  | 'unknown'
