// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
// Generated on: 2026-07-27T08:54:32.663Z
// Run "node scripts/generate-docs.js" to regenerate.

export const GENERATED_INTERFACES: Record<string, string> = {
  "PluginChatItem": "interface PluginChatItem {\n    jid: string;\n    name?: string;\n    unreadCount?: number;\n    isArchived?: boolean;\n    isPinned?: boolean;\n    isMuted?: boolean;\n    lastMessageTimestamp?: number;\n}",
  "PluginMessageItem": "interface PluginMessageItem {\n    id: string;\n    chatJid: string;\n    senderJid: string;\n    fromMe: boolean;\n    text: string | null;\n    timestamp: number;\n}",
  "PluginContactItem": "interface PluginContactItem {\n    jid: string;\n    name?: string;\n    pushName?: string;\n}",
  "SendMessageOptions": "interface SendMessageOptions {\n    quotedMessageId?: string;\n}",
  "AICallOptions": "interface AICallOptions {\n    temperature?: number;\n    model?: string;\n}",
  "ChatActionContext": "interface ChatActionContext {\n    chatJid: string;\n}",
  "MessageActionContext": "interface MessageActionContext {\n    chatJid: string;\n    messageId: string;\n}",
  "CommandContext": "interface CommandContext {\n    chatJid?: string;\n}",
  "BadgeDescriptor": "interface BadgeDescriptor {\n    text?: string;\n    count?: number;\n    color?: string;\n}",
  "CompletionContext": "interface CompletionContext {\n    text: string;\n    cursorPosition: number;\n}",
  "CompletionItem": "interface CompletionItem {\n    label: string;\n    insertText: string;\n    detail?: string;\n}",
  "OutgoingMessagePayload": "interface OutgoingMessagePayload {\n    chatJid: string;\n    text: string;\n}",
  "SendResult": "interface SendResult {\n    success: boolean;\n    messageId?: string;\n}",
  "IPluginLogAPI": "interface IPluginLogAPI {\n    info(msg: string, ...data: unknown[]): void;\n    warn(msg: string, ...data: unknown[]): void;\n    error(msg: string, ...data: unknown[]): void;\n}",
  "IPluginChatsAPI": "interface IPluginChatsAPI {\n    getList(page?: number, limit?: number): Promise<PluginChatItem[]>;\n    getById(jid: string): Promise<PluginChatItem | null>;\n    pin(jid: string): Promise<void>;\n    unpin(jid: string): Promise<void>;\n    archive(jid: string): Promise<void>;\n    unarchive(jid: string): Promise<void>;\n    mute(jid: string, durationMs: number): Promise<void>;\n    unmute(jid: string): Promise<void>;\n    markRead(jid: string): Promise<void>;\n}",
  "IPluginMessagesAPI": "interface IPluginMessagesAPI {\n    getMessages(jid: string, page?: number, limit?: number): Promise<PluginMessageItem[]>;\n    send(jid: string, text: string, options?: SendMessageOptions): Promise<PluginMessageItem>;\n    delete(jid: string, messageId: string): Promise<void>;\n    react(jid: string, messageId: string, emoji: string): Promise<void>;\n}",
  "IPluginContactsAPI": "interface IPluginContactsAPI {\n    getByJid(jid: string): Promise<PluginContactItem | null>;\n}",
  "IPluginEventsAPI": "interface IPluginEventsAPI {\n    on<K extends PluginEventName>(event: K, handler: (payload: PluginEventMap[K]) => void | Promise<void>): () => void;\n}",
  "IPluginStorageAPI": "interface IPluginStorageAPI {\n    get<T = unknown>(key: string): Promise<T | undefined>;\n    set(key: string, value: unknown): Promise<void>;\n    delete(key: string): Promise<void>;\n    clear(): Promise<void>;\n    keys(): Promise<string[]>;\n}",
  "IPluginSchedulerAPI": "interface IPluginSchedulerAPI {\n    setInterval(ms: number, fn: () => void | Promise<void>): () => void;\n    setTimeout(ms: number, fn: () => void | Promise<void>): () => void;\n}",
  "IPluginUIAPI": "interface IPluginUIAPI {\n    notify(opts: {\n        title: string;\n        body: string;\n    }): Promise<void>;\n    toast(msg: string, level?: 'info' | 'success' | 'warning' | 'error'): void;\n}",
  "IPluginAIAPI": "interface IPluginAIAPI {\n    chat(prompt: string, options?: AICallOptions): Promise<string>;\n    callTool(toolName: string, args: Record<string, unknown>): Promise<{\n        text: string;\n    }>;\n}",
  "IPluginContributionsAPI": "interface IPluginContributionsAPI {\n    registerChatAction(id: string, handler: (ctx: ChatActionContext) => Promise<void>): void;\n    registerMessageAction(id: string, handler: (ctx: MessageActionContext) => Promise<void>): void;\n    registerChatBadge(id: string, compute: (chatJid: string) => Promise<BadgeDescriptor | null>): void;\n    registerSlashCommand(name: string, handler: (args: string, context: CommandContext) => Promise<void>): void;\n    registerAITool(name: string, execute: (args: Record<string, unknown>) => Promise<{\n        text: string;\n    }>): void;\n    registerCompletionProvider(id: string, provide: (ctx: CompletionContext) => Promise<CompletionItem[]>): void;\n    registerMessageSendInterceptor(id: string, intercept: (payload: OutgoingMessagePayload, next: (payload: OutgoingMessagePayload) => Promise<SendResult>) => Promise<SendResult>): void;\n    exposeAPI(exportName: string, api: Record<string, unknown>): void;\n    importAPI(pluginId: string, exportName: string): Promise<Record<string, unknown>>;\n}",
  "PluginContext": "interface PluginContext {\n    readonly id: string;\n    readonly manifest: PluginManifest;\n    onActivate(fn: () => Promise<void>): void;\n    onDeactivate(fn: () => Promise<void>): void;\n    readonly log: IPluginLogAPI;\n    readonly chats?: IPluginChatsAPI;\n    readonly messages?: IPluginMessagesAPI;\n    readonly contacts?: IPluginContactsAPI;\n    readonly ai?: IPluginAIAPI;\n    readonly events?: IPluginEventsAPI;\n    readonly storage?: IPluginStorageAPI;\n    readonly ui?: IPluginUIAPI;\n    readonly scheduler?: IPluginSchedulerAPI;\n    readonly contributions: IPluginContributionsAPI;\n}",
  "PluginMessageIncomingEvent": "interface PluginMessageIncomingEvent {\n    chatJid: string;\n    senderJid: string;\n    textContent: string | null;\n    fromMe: boolean;\n    timestamp: bigint;\n    enriched?: unknown;\n}",
  "PluginMessageDeletedEvent": "interface PluginMessageDeletedEvent {\n    messageId: string;\n    chatJid: string;\n    fromMe: boolean;\n}",
  "PluginMessageEditedEvent": "interface PluginMessageEditedEvent {\n    messageId: string;\n    chatJid: string;\n    fromMe: boolean;\n    participant: string | null;\n    editedTextContent: string | null;\n}",
  "PluginMessageStatusUpdatedEvent": "interface PluginMessageStatusUpdatedEvent {\n    id: string;\n    chatJid: string;\n    status: string;\n}",
  "PluginReactionProcessedEvent": "interface PluginReactionProcessedEvent {\n    id: string;\n    chatJid: string;\n    remoteJid: string;\n    fromMe: boolean;\n    senderId: number | null;\n    participant: string;\n    participantName: string;\n    timestamp: string;\n    messageType: 'reactionMessage';\n    targetMessageType?: string;\n    targetTextContent?: string | null;\n    content: string;\n}",
  "PluginChatCreatedEvent": "interface PluginChatCreatedEvent {\n    jid: string;\n    name?: string;\n}",
  "PluginChatArchivedEvent": "interface PluginChatArchivedEvent {\n    jid: string;\n    archived: boolean;\n}",
  "PluginChatPinnedEvent": "interface PluginChatPinnedEvent {\n    jid: string;\n    pinned: boolean;\n}",
  "PluginContactUpdatedEvent": "interface PluginContactUpdatedEvent {\n    jid: string;\n    name?: string;\n    pushName?: string;\n}",
  "PluginGroupParticipantAddedEvent": "interface PluginGroupParticipantAddedEvent {\n    id: string;\n    participants: string[];\n}",
  "PluginGroupParticipantRemovedEvent": "interface PluginGroupParticipantRemovedEvent {\n    id: string;\n    participants: string[];\n}",
  "PluginGroupSubjectChangedEvent": "interface PluginGroupSubjectChangedEvent {\n    id: string;\n    subject: string;\n}",
  "PluginConnectionOpenEvent": "interface PluginConnectionOpenEvent {\n}",
  "PluginConnectionCloseEvent": "interface PluginConnectionCloseEvent {\n}",
  "PluginEventMap": "interface PluginEventMap {\n    'message:incoming': PluginMessageIncomingEvent;\n    'message:deleted': PluginMessageDeletedEvent;\n    'message:edited': PluginMessageEditedEvent;\n    'message:status-updated': PluginMessageStatusUpdatedEvent;\n    'reaction:processed': PluginReactionProcessedEvent;\n    'chat:created': PluginChatCreatedEvent;\n    'chat:archived': PluginChatArchivedEvent;\n    'chat:pinned': PluginChatPinnedEvent;\n    'contact:updated': PluginContactUpdatedEvent;\n    'group:participant-added': PluginGroupParticipantAddedEvent;\n    'group:participant-removed': PluginGroupParticipantRemovedEvent;\n    'group:subject-changed': PluginGroupSubjectChangedEvent;\n    'connection:open': PluginConnectionOpenEvent;\n    'connection:close': PluginConnectionCloseEvent;\n    [key: string]: unknown;\n}",
  "PluginEventName": "type PluginEventName = Extract<keyof PluginEventMap, string>;",
  "SlashCommand": "interface SlashCommand {\n    name: string;\n    description: string;\n}",
  "CronEntry": "interface CronEntry {\n    name: string;\n    cron: string;\n}",
  "PermissionCapability": "type PermissionCapability = string;",
  "ContributionsDeclaration": "interface ContributionsDeclaration {\n    chatActions?: Array<{\n        id: string;\n        label: string;\n        icon?: string;\n        when?: string;\n    }>;\n    messageActions?: Array<{\n        id: string;\n        label: string;\n        icon?: string;\n        when?: string;\n    }>;\n    chatBadges?: Array<{\n        id: string;\n        label?: string;\n    }>;\n    messageRenderers?: Array<{\n        id: string;\n        messageType: string;\n    }>;\n    slashCommands?: SlashCommand[];\n    sidebarPanels?: Array<{\n        id: string;\n        title: string;\n        icon?: string;\n        panel?: string;\n    }>;\n    settingsPages?: Array<{\n        id: string;\n        title: string;\n        panel?: string;\n    }>;\n    aiTools?: Array<{\n        name: string;\n        description: string;\n        schema: object;\n    }>;\n    keyboardShortcuts?: Array<{\n        id: string;\n        defaultBinding: string;\n        description: string;\n    }>;\n    statusBarItems?: Array<{\n        id: string;\n        alignment: 'left' | 'right';\n    }>;\n    chatFilters?: Array<{\n        id: string;\n        label: string;\n        icon?: string;\n    }>;\n    chatSortStrategies?: Array<{\n        id: string;\n        label: string;\n    }>;\n    completionProviders?: Array<{\n        id: string;\n        trigger: string;\n        context: 'chatbar' | 'search';\n    }>;\n    messageSendPipeline?: Array<{\n        id: string;\n        priority: number;\n    }>;\n    pluginApiExports?: string[];\n}",
  "PluginManifest": "interface PluginManifest {\n    id: string;\n    name: string;\n    version: string;\n    apiVersion: '2';\n    main: string;\n    permissions: PermissionCapability[];\n    contributions: ContributionsDeclaration;\n    description?: string;\n    scheduler?: {\n        onStart: boolean;\n        intervals: CronEntry[];\n    };\n}"
};

export interface GeneratedEventInfo {
  name: string;
  payloadInterface: string;
  payloadDef: string;
}

export const GENERATED_EVENTS: GeneratedEventInfo[] = [
  {
    "name": "message:incoming",
    "payloadInterface": "PluginMessageIncomingEvent",
    "payloadDef": "interface PluginMessageIncomingEvent {\n    chatJid: string;\n    senderJid: string;\n    textContent: string | null;\n    fromMe: boolean;\n    timestamp: bigint;\n    enriched?: unknown;\n}"
  },
  {
    "name": "message:deleted",
    "payloadInterface": "PluginMessageDeletedEvent",
    "payloadDef": "interface PluginMessageDeletedEvent {\n    messageId: string;\n    chatJid: string;\n    fromMe: boolean;\n}"
  },
  {
    "name": "message:edited",
    "payloadInterface": "PluginMessageEditedEvent",
    "payloadDef": "interface PluginMessageEditedEvent {\n    messageId: string;\n    chatJid: string;\n    fromMe: boolean;\n    participant: string | null;\n    editedTextContent: string | null;\n}"
  },
  {
    "name": "message:status-updated",
    "payloadInterface": "PluginMessageStatusUpdatedEvent",
    "payloadDef": "interface PluginMessageStatusUpdatedEvent {\n    id: string;\n    chatJid: string;\n    status: string;\n}"
  },
  {
    "name": "reaction:processed",
    "payloadInterface": "PluginReactionProcessedEvent",
    "payloadDef": "interface PluginReactionProcessedEvent {\n    id: string;\n    chatJid: string;\n    remoteJid: string;\n    fromMe: boolean;\n    senderId: number | null;\n    participant: string;\n    participantName: string;\n    timestamp: string;\n    messageType: 'reactionMessage';\n    targetMessageType?: string;\n    targetTextContent?: string | null;\n    content: string;\n}"
  },
  {
    "name": "chat:created",
    "payloadInterface": "PluginChatCreatedEvent",
    "payloadDef": "interface PluginChatCreatedEvent {\n    jid: string;\n    name?: string;\n}"
  },
  {
    "name": "chat:archived",
    "payloadInterface": "PluginChatArchivedEvent",
    "payloadDef": "interface PluginChatArchivedEvent {\n    jid: string;\n    archived: boolean;\n}"
  },
  {
    "name": "chat:pinned",
    "payloadInterface": "PluginChatPinnedEvent",
    "payloadDef": "interface PluginChatPinnedEvent {\n    jid: string;\n    pinned: boolean;\n}"
  },
  {
    "name": "contact:updated",
    "payloadInterface": "PluginContactUpdatedEvent",
    "payloadDef": "interface PluginContactUpdatedEvent {\n    jid: string;\n    name?: string;\n    pushName?: string;\n}"
  },
  {
    "name": "group:participant-added",
    "payloadInterface": "PluginGroupParticipantAddedEvent",
    "payloadDef": "interface PluginGroupParticipantAddedEvent {\n    id: string;\n    participants: string[];\n}"
  },
  {
    "name": "group:participant-removed",
    "payloadInterface": "PluginGroupParticipantRemovedEvent",
    "payloadDef": "interface PluginGroupParticipantRemovedEvent {\n    id: string;\n    participants: string[];\n}"
  },
  {
    "name": "group:subject-changed",
    "payloadInterface": "PluginGroupSubjectChangedEvent",
    "payloadDef": "interface PluginGroupSubjectChangedEvent {\n    id: string;\n    subject: string;\n}"
  },
  {
    "name": "connection:open",
    "payloadInterface": "PluginConnectionOpenEvent",
    "payloadDef": "interface PluginConnectionOpenEvent {\n}"
  },
  {
    "name": "connection:close",
    "payloadInterface": "PluginConnectionCloseEvent",
    "payloadDef": "interface PluginConnectionCloseEvent {\n}"
  }
];
